#!/bin/sh

echo "==============================================="
echo "🏃 Menjalankan Pre-push Hook (Lint & Unit Test)"
echo "==============================================="

./gradlew spotlessCheck detekt testDebugUnitTest

status=$?

if [ "$status" = 0 ] ; then
    echo "✅ Semua tes berhasil. Memproses push..."
    exit 0
else
    echo "❌ Terjadi kesalahan pada Linting atau Unit Test."
    echo "Pesan: Harap perbaiki kode Anda sebelum melakukan push."
    echo "Gunakan './gradlew spotlessApply' jika format kode salah."
    exit 1
fi
